# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlutterHybridiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
##  use_frameworks!
#flutter_application_path = '../flutter_module/'
#load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  flutter_application_path = '../flutter_module/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
#  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


  target 'FlutterHybridiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterHybridiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
